preserve_hierarchy: 1
files:
  - source: /Resources/Private/Language/*.xlf
    ignore:
      - /**/%two_letters_code%.%original_file_name%
    translation: /%original_path%/%two_letters_code%.%original_file_name%
